project:
  type: website

website:
  title: "farganaislamblog"
  google-analytics: "G-0EDDZS927G"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/farganaislam
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - lux
    css: styles.css

editor: visual

